version: 2

run:
  timeout: 3m

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 5
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: 100
    statements: 50

linters:
  enable:
    # Default linters (automatically enabled)
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional useful linters
    - misspell
    - goconst
    - gocyclo
    - funlen
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - funlen